In [ ]:
import numpy as np
arr=np.array([[1,2,3,8],
              [4,5,6,7]])
print(arr.shape) #no.of rows & cols
print(arr.size)  #no. of eles


(2, 4)
8
2


In [9]:
import numpy as np
arr1=np.array([8,9,10])
arr2=np.array([[1,2,3,8],[4,5,6,7]])
arr3=np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(arr1.ndim) #no. of dimensons
print(arr2.ndim)
print(arr3.ndim)
print(arr1.dtype) #data type of eles of array

1
2
3
int64


In [23]:
import numpy as np
arr1=np.array([8.7,9.1,10.02])
arr2=arr1.astype(int)
arr3=arr1.astype(str)
print(arr2,arr2.dtype)
print(arr3,arr3.dtype)

[ 8  9 10] int64
['8.7' '9.1' '10.02'] <U32


In [21]:
#Operations
import numpy as np
arr1=np.array([8,9,10])

print(arr1+5)
print(arr1*5)
print(arr1-5)
print(arr1**2)
print(arr1/2)
print(arr1%2)

[13 14 15]
[40 45 50]
[3 4 5]
[ 64  81 100]
[4.  4.5 5. ]
[0 1 0]


In [ ]:
#Aggregation 
import numpy as np
arr=np.array([1,2,3])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))
#standard deviation=underroot((sum of(x-xbar)*(x-xbar))/n)
#xbar=average
#variance=(sum of(x-xbar)*(x-xbar))/n

6
2.0
1
3
0.816496580927726
0.6666666666666666
